# Generated by Django 4.2.5 on 2023-11-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userservice',
            name='active_date',
            field=models.DateField(default='2023-11-07'),
        ),
    ]
