# Generated by Django 4.2.5 on 2023-11-06 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(default='2023-11-06T23:43:29Z'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='expired_at',
            field=models.DateTimeField(default='2023-11-07T00:43:29Z'),
        ),
    ]
