# Generated by Django 4.2.5 on 2023-11-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_transaction_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(default='2023-11-07T17:09:17Z'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='expired_at',
            field=models.DateTimeField(default='2023-11-07T18:09:17Z'),
        ),
    ]
