services:
  web_app:
    container_name: provider_app
    environment:
      DJANGO_SETTINGS_MODULE: provider_project.settings
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db_container

  db_container:
    hostname: pg_provider
    container_name: pg_provider
    build:
      context: .
      dockerfile: Dockerfile_pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: provider
    ports:
      - 5432:5432
#
#  celery_worker:
#    hostname: celery_worker
#    build: .
#    command: celery -A celery_tasks.celery worker --loglevel=info --pool=solo
#    depends_on:
#      - db_container
#      - rabbit_mq
#    env_file: .env
#
#  rabbit_mq:
#    hostname: rabbit_mq
#    image: rabbitmq:3-management
#    environment:
#      RABBIT_DEFAULT_USER: guest
#      RABBIT_DEFAULT_pass: guest
#    ports:
#    - "5672:5672"
#    - "15672:15672"
